#!/usr/bin/env python3
# addons/signoz/enable

import os
import subprocess

import click

DEFAULT_NAMESPACE = "signoz"
KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
HELMCTL = os.path.expandvars("$SNAP/microk8s-helm.wrapper")
MICROK8S_STATUS = os.path.expandvars("$SNAP/microk8s-status.wrapper")


@click.command()
@click.option("--version", required=False, default="0.68.1", type=str)
@click.option("--namespace", required=False, default=DEFAULT_NAMESPACE, type=str)
@click.option("--values", required=False, default="", type=str)
def main(version, namespace, collector_image, values):
    click.echo("Enabling signoz")

    subprocess.check_call(
        [
            HELMCTL,
            "repo",
            "add",
            "signoz",
            "https://charts.signoz.io",
        ]
    )

    install_args = [
        HELMCTL,
        "upgrade",
        "--install",
        "signoz",
        "signoz/signoz",
        "--namespace",
        namespace,
        "--create-namespace",
        "--version",
        version,
    ]

    if values:
        click.echo(f"Using provided values file: {values}")
        install_args.extend(["-f", values])

    subprocess.check_call(install_args)

    click.echo("Enabled signoz")


if __name__ == "__main__":
    main()
